out_dir: "numbers-runs/tfri-pair-4/clone-e"

out_plots:
  cnv: True
  baf: True

data:
  plasma_read_counts: "/home/matteo/Desktop/anything-numbers-pulls/cfclone-pulls/pull034/numbers-runs/tfri-pair-4/clone-e/read_counts/read_counts.wig"
  plasma_allele_counts: "/home/matteo/Desktop/anything-numbers-pulls/cfclone-pulls/pull034/numbers-runs/tfri-pair-4/clone-e/allele_counts/results/counts/allele_counts.tsv.gz"

blacklist_regions_file: "references/blacklist_2018.10.23.txt"

cnv:
  gc_file: "references/b37_autosomes_500k.gc.wig"
  map_file: "references/b37_autosomes_500k.map.wig"