out_dir: "numbers-runs/ovarian-case-1/VOA15710P"

out_plots:
  cnv: True
  baf: True

data:
  plasma_read_counts: "/home/matteo/Desktop/anything-numbers-pulls/cfclone-pulls/pull035/numbers-runs/ovarian-case-1/VOA15710P/read_counts/read_counts.wig"
  plasma_allele_counts: "/home/matteo/Desktop/anything-numbers-pulls/cfclone-pulls/pull035/numbers-runs/ovarian-case-1/VOA15710P/allele_counts/results/counts/allele_counts.tsv.gz"

blacklist_regions_file: "references/blacklist_2018.10.23.txt"

cnv:
  gc_file: "references/b37_autosomes_500k.gc.wig"
  map_file: "references/b37_autosomes_500k.map.wig"