out_dir: "results/smoke-test"
plasma_read_counts: "smoke-test-data/read_counts.wig"
plasma_allele_counts: "smoke-test-data/allele_counts.tsv"
plots:
  cnv: True
  baf: False
exclude_regions:
baf:
cnv:
  gc_file: "smoke-test-data/b37_500k.gc.wig"
  map_file: "smoke-test-data/b37_500k.map.wig"