out_dir: "runs/tnbc/CID0000391/F112602"

out_plots:
  cnv: True
  baf: True

data:
  plasma_read_counts: "tnbc-data/CID0000391/F112602.wig"
  plasma_allele_counts: "/home/matteo/Desktop/anything-numbers-pulls/cfclone-pulls/pull036/numbers-runs/tnbc/CID0000391/F112602/allele_counts/results/counts/allele_counts.tsv.gz"

reference_genome: "hg38"
blacklist_regions_file: "references/blacklist_GRCh38.GCA_000001405.2_centromere_acen.txt"
cnv:
  gc_file: "references/gc_hg38_1000kb_autosomes.wig"
  map_file: "references/map_hg38_1000kb_autosomes.wig"